// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBay3BB3dSrLHiO4BYte4740ASAmU59Slg',
    appId: '1:835711318561:web:7c08d59e5459330d608160',
    messagingSenderId: '835711318561',
    projectId: 'cofit-400b2',
    authDomain: 'cofit-400b2.firebaseapp.com',
    storageBucket: 'cofit-400b2.firebasestorage.app',
    measurementId: 'G-6ZZBQJ3C5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWlhaCUW770_FtN-gfbYV5_bNcLt6vaQ',
    appId: '1:835711318561:android:16e942745bc4fb46608160',
    messagingSenderId: '835711318561',
    projectId: 'cofit-400b2',
    storageBucket: 'cofit-400b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYzlY7hk5kBXxqDWWylYusXa6tmKhMf8',
    appId: '1:835711318561:ios:0d22d56f7a879e43608160',
    messagingSenderId: '835711318561',
    projectId: 'cofit-400b2',
    storageBucket: 'cofit-400b2.firebasestorage.app',
    iosBundleId: 'com.example.cofitCollective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKYzlY7hk5kBXxqDWWylYusXa6tmKhMf8',
    appId: '1:835711318561:ios:0d22d56f7a879e43608160',
    messagingSenderId: '835711318561',
    projectId: 'cofit-400b2',
    storageBucket: 'cofit-400b2.firebasestorage.app',
    iosBundleId: 'com.example.cofitCollective',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBay3BB3dSrLHiO4BYte4740ASAmU59Slg',
    appId: '1:835711318561:web:60ef8a05aa09e963608160',
    messagingSenderId: '835711318561',
    projectId: 'cofit-400b2',
    authDomain: 'cofit-400b2.firebaseapp.com',
    storageBucket: 'cofit-400b2.firebasestorage.app',
    measurementId: 'G-HE9JY85T4F',
  );
}
